Feat/#3-S : 로그인 페이지 구현 & 절대 경로 설정
boostcampwm-2022/web27-Wabinar pull request #11
Opened 2022-11-14 13:14 UTC by juyeong-s

## 🤠 개요

- resolve #3 

## 💫 설명

- tsconfig, vite.config 두 개 파일에 모두 절대 경로를 설정해주어야 한대요
- 버튼 컴포넌트를 `components/common` 안에 생성했는데, 공통적으로 사용할 만한 컴포넌트는 common에 두고 사용해요! 그 외에는 바깥에 두어도 좋아요
- 로그인 페이지 UI 구현
- `common/Icon` 같은 경우, 로고나 깃허브 이모티콘 같은 경우 `react-icons`으로 사용할 수 없어서 `common/Icon`에 모아두려고 하는데 괜찮나요?
  - react-icons 에서 가져다 사용할 수 없는 것들이 또 있으면 여기에서 사용하면 될 것 같아요

## 🌜 고민거리 (Optional)

## 📷 스크린샷 (Optional)
- 로그인 페이지
![스크린샷 2022-11-14 오후 10 11 35](https://user-images.githubusercontent.com/63364990/201668700-3235ff13-0842-47e7-8f3c-83530ff28830.png)
- 버튼 공통 컴포넌트

| 아이콘이 있는 경우 |  아이콘이 없는 경우 |
|--|--|
|  ![스크린샷 2022-11-14 오후 9 52 25](https://user-images.githubusercontent.com/63364990/201668962-bb26ecc8-4a47-40f3-99d4-0422f8d15611.png) |  ![스크린샷 2022-11-14 오후 9 52 39](https://user-images.githubusercontent.com/63364990/201668979-79dffdc7-997f-48f4-9da9-6e74739fc7cf.png)  |

2022-11-14 13:41 UTC, dohun31 requested changes
common 만드신거 너무 좋아요 👍

2022-11-14 13:41 UTC, dohun31 commented on client/src/components/common/Button/index.tsx
> +import $ from "./style.module.scss";
저희 style로 통일해요!

2022-11-14 16:29 UTC, se030 approved these changes

2022-11-15 01:06 UTC, dohun31 approved these changes

2022-11-15 01:06 UTC, merged