Feat/#37-K: 로그인 API 연동
boostcampwm-2022/web27-Wabinar pull request #42
Opened 2022-11-15 15:29 UTC by se030

## 🤠 개요

- resolve #37 
- 클라이언트에 로그인 API를 연동하고 UserContext를 사용해 로그인 상태를 유지하도록 했어요.

## 💫 설명

서버의 auth API를 사용해 클라이언트 로그인 기능을 구현했어요.

- 로그인 버튼을 클릭하면 auth code를 발급할 수 있는 OAuth Application로 연결
  `<a href="https://github.com/login/oauth/authorize?client_id=${env.GITHUB_CLIENT_ID}" />`
- github 사용자 인증이 끝나면 `왜비나/oauth`로 리다이렉트 (OAuth Application callback url 설정)
- search params의 code를 사용해 `서버/auth/login`에 로그인 요청
  - 성공 시 `왜비나/workspace`, 실패 시 인덱스 페이지로 리다이렉션

<br />

- **dotenv-vault 들이 많이 변동되었어요. pull 받아두세요!**
- 클라이언트 `styles/color.scss`를 js에서 사용할 일이 있어 모듈로 변경했어요.
- 클라이언트 절대경로 설정 중 `style`을 `styles`로 변경했어요. 실제 폴더명과 같게요.
- 클라이언트 api 폴더에 http status code 상수 모듈이 생겼어요.
- 서버에 cors 미들웨어가 생겼어요.
  저희 클라이언트 어플리케이션이 서버와 이상없이 통신하도록 필요한 헤더들, 그리고 쿠키를 사용하기 위해 필요한 헤더를 추가해주는 친구에요. 브라우저의 preflight 요청에 OK 응답을 보내주는 로직이 포함되어 있어요. [참고 자료](https://evan-moon.github.io/2020/05/21/about-cors/)

## 🌜 고민거리 (Optional)

Q. 타입 관련 이슈가 있는데 해결방법을 아시는 분이 있나요? 인터페이스는 아래 사진에 이어서 첨부했어요.
<img width="769" alt="image" src="https://user-images.githubusercontent.com/63814960/201957574-8d56df58-3e6e-41c0-949e-a28b7b674817.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/63814960/201957723-613a8fda-0876-4fca-8486-7ba5b9a3ec8e.png">

Q. common/Button 컴포넌트에서 href 속성에 따라 분기하는 부분이 어색하게 느껴지는데 분리하는게 좋을까요?
to. 주영님.. onClick으로 넣으려다가 지저분해서 a tag로 다시 바꿨어요.

## 📷 스크린샷
![Nov-16-2022 00-13-01](https://user-images.githubusercontent.com/63814960/201955114-17cc9e87-98fd-420f-8dd0-6034e19b8fb6.gif)

<br />

P.S. 프로젝트 초반이라 새로 만든 설정 관련 파일, util들이 여기저기서 필요해서 PR끼리 더 꼬이는 것 같아요.
도훈님 PR에서 사용할 util들이 있어서 pull 했더니 또 로그가 지저분하네요 ㅠㅠ 커밋 저렇게 많은게 이런 애들 때문인 것 같은..

2022-11-15 21:47 UTC, juyeong-s approved these changes

2022-11-15 21:47 UTC, juyeong-s commented on client/src/apis/auth.ts
> +};
users api 쪽에 try/catch 문 없애고 이렇게 통일해서 써요!

2022-11-16 01:00 UTC, dohun31 requested changes
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/65100540/202057445-40bb8fbe-346c-4ce4-898d-4f1e1c9557ce.png">

여기 확인해주세요!

2022-11-16 01:01 UTC, dohun31 commented
```txt
Error: src/components/WorkspaceModal/index.tsx(31,32): error TS2322: Type '{ text: string; isDisable: boolean; }' is not assignable to type 'IntrinsicAttributes & ButtonProps'.
  Property 'isDisable' does not exist on type 'IntrinsicAttributes & ButtonProps'. Did you mean 'isDisabled'?
```

2022-11-16 01:41 UTC, juyeong-s commented
> <img alt="image" width="1224" src="https://user-images.githubusercontent.com/65100540/202057445-40bb8fbe-346c-4ce4-898d-4f1e1c9557ce.png">
> 
> 여기 확인해주세요!

근데 이거 왜 오류없이 잘 돌아가죠?

2022-11-16 02:49 UTC, dohun31 approved these changes

2022-11-16 02:52 UTC, merged