Feat/#98-B: 클립보드 복사 버튼 구현
boostcampwm-2022/web27-Wabinar pull request #99
Opened 2022-11-19 09:36 UTC by dohun31

## 🤠 개요

- resolve: #98

## 💫 설명

클립보드 복사 버튼이 생성  완료 모달과 설정 모달에서 공통으로 사용되길래 common 컴포넌트로 만들었어요.
- target text를 props로 전달해주세요.
- className을 적용하려면 전달해주세요.
```typescript
interface CopyButton {
  target: string;
  className?: string;
}
```

## 🌜 고민거리 (Optional)

## 📷 스크린샷 (Optional)

2022-11-19 09:37 UTC, juyeong-s commented
부장님 주말에 뭐하시는거에요

2022-11-19 09:53 UTC, se030 approved these changes

2022-11-19 16:35 UTC, juyeong-s requested changes

2022-11-19 16:35 UTC, juyeong-s commented on client/src/components/common/CopyButton/index.tsx
> +import React from 'react';
안쓰는 React 없어도 될 거 같아요ㅎㅎ

2022-11-19 16:35 UTC, juyeong-s commented on client/src/components/common/CopyButton/index.tsx
> +import React from 'react';
VScode에 setting.json에 이렇게 추가해주면 자동으로 없애주더라고요
```json
 "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
```

2022-11-19 16:35 UTC, juyeong-s commented on client/src/components/common/CopyButton/index.tsx
> +interface CopyButton {
네이밍이 뒤에 Props가 필요할 거 같아요

2022-11-20 02:53 UTC, dohun31 commented on client/src/components/common/CopyButton/index.tsx
> +interface CopyButton {
헐 어떻게 이런 실수를 했죠 ㅋㅋㅋㅋㅋㅋㅋ 얼른 고칠게요

2022-11-20 14:19 UTC, juyeong-s approved these changes

2022-11-21 05:34 UTC, wcho21 approved these changes

2022-11-21 05:35 UTC, merged